- API/PirateText.py
- API/responseLocal.py
Minor changes to the text thresholds as per https://github.com/Pirate-Weather/pirateweather/issues/152#issuecomment-2508080553
> Update text thresholds

- API/PirateDailyText.py
- API/PirateMinutelyText.py
- API/PirateWeeklyText.py
This PR adds the code I created for the weekly, daily/hourly and minutely summaries to the repo. I haven't added any code to get the API to generate these summaries as I am unable to run the code (I've mentioned this before).
- This pull request fixes issue: fixes #41, fixes #42 and fixes #45
> Add other summaries

- .github/workflows/lint.yml
- API/NBM_Fire_Local_Ingest.py
- API/NBM_Local_Ingest.py
- API/NWS_Alerts_Local.py
- API/responseLocal.py
- API/timemachine2.py
@alexander0042 A quick PR to fix some miscellaneous precipitation issues that I've noticed and should help with https://github.com/Pirate-Weather/pirateweather/issues/415
1. I changed the minutely data so that if pop is < 5% then its set to 0 as already done on the hourly data.
2. Since GEFS can sometimes forecast precipitation with 0 probability the minutely intensity gets set to 0 to match the hourly data
3. Set precipitation accumulation to 0 when there is 0 pop as already done for intensity. This just makes it so the summaries don't mention rain with no intensity.
Should all work but again I haven't tested it.
> Miscellaneous precipitation fixes

- API/PirateText.py
Small fix to remove the possible text generating on days with multiple precipitation types forecasted.
> Fix possible text generating on days with multiple precipitation types

- .github/workflows/lint.yml
- .gitignore
- API/NBM_Fire_Local_Ingest.py
- API/NBM_Local_Ingest.py
- API/NWS_Alerts_Local.py
- API/PirateText.py
- API/responseLocal.py
- API/timemachine2.py
> API Version 2.5.3

- .github/workflows/sanity.yml
- Docker/pirate-ingest-dockerfile
- Docker/requirements-ingest.txt
Thanks for making this project. Really cool work.
I was working getting running on my own hardware and I made some changes to get containers to build. I figured I would add some tests while I was at it. :)
This PR adds a GitHub job to build the ingest and api containers. The CI job doesn't push anywhere, however we could easily push to the GitHub registry if you wanted. If you want to push to AWS that would require a bit more setup but should be doable.
- This pull request partially addresses issue: #60
> Add CI and fix Docker build

- .github/workflows/build.yml
- .github/workflows/sanity.yml
Use multiple build nodes to build ARM and x64 images, as it's much faster than QEMU
> Add in Multi Arch Build and Push

- API/PirateDailyText.py
- API/PirateMinutelyText.py
- API/PirateSimpleDayText.py
- API/responseLocal.py
I've updated the proper daily summaries function to work with the hour dicts that are being used elsewhere and updated the precipitation summaries to work like the simple daily ones.
I've tested using my summary generator and it works for the hourly block but I don't have anything setup to test for the day blocks. Might be able to set something up but it might be complicated. You may need to change the format slightly if you need to send the data in a different format.
I still need to comment the new code and possibly move the loop code to its own function but I can do that later if needed. Have this as a draft as it needs to be more thoroughly tested.
> Updated day summaries

- .github/workflows/codeql.yml
- API/NBM_Local_Ingest.py
> Fix CodeQL not running on PRs

- .gitignore
- API/responseLocal.py
Fix for timezone issue https://github.com/Pirate-Weather/pirateweather/issues/458.
Also updated the STAGE=TESTING parameter to allow the response container to query the zarr files in my S3 bucket directly! This should allow for the response container to be run standalone, simplifying development.
The current remote zarr implementation is very alpha, and subject to be changed at any point. It also hammers API key requests pretty aggressively, so keep that in mind. In the medium term I'm hoping to switch over to [Xpublish](https://xpublish.readthedocs.io/en/0.4.1/l), since it will allow for much better mapping support!
- This pull request fixes issue: fixes https://github.com/Pirate-Weather/pirateweather/issues/458
> Fix half hour zone issue and allow for remote zarr access!

- API/GEFS_Local_Ingest.py
- API/GFS_Local_Ingest.py
- API/HRRR_6H_Local_Ingest.py
- API/HRRR_Local_Ingest.py
- API/NBM_Fire_Local_Ingest.py
- API/NBM_Local_Ingest.py
- API/SubH_Local_Ingest.py
Make it so all calls to wgrib2 will exit the script if they fail.
ea
> Handle all wgrib2 calls to exit if they fail

- API/PirateDailyText.py
@alexander0042 Looks like I messed up the `maxWind` calculation and it was only ever using the wind speed from the first period even if ones afterwards had a higher wind speed. I think it should fix the summary gen issues you were seeing.
> Fix maxWind calculations

- API/ECMWF_Local_Ingest.py
- API/GEFS_Local_Ingest.py
- API/GFS_Local_Ingest.py
- API/HRRR_6H_Local_Ingest.py
- API/HRRR_Local_Ingest.py
- API/NBM_Fire_Local_Ingest.py
- API/NBM_Local_Ingest.py
- API/NWS_Alerts_Local.py
- API/SubH_Local_Ingest.py
Noticed a lot of very small (~E-16) values in the final zarrs, likely as a result of interpolation. Added a dask rounding step to try to eliminate this and see the impact on file size
> Add rounding to improve compression

- API/ECMWF_Local_Ingest.py
- API/GEFS_Local_Ingest.py
- API/GFS_Local_Ingest.py
- API/HRRR_6H_Local_Ingest.py
- API/HRRR_Local_Ingest.py
- API/NBM_Fire_Local_Ingest.py
- API/NBM_Local_Ingest.py
Turns out all that was wrong with the previous approach was that I was passing the wrong shape to dask map_blocks, so that it only interpolated over a fraction of the array. This update fixes it and introduces a new linear interpolation approach that improves performance a bit as well.
> Interp fix

- README.md
Small update to the docs to remove the node setup from the VEnv docs
- This pull request fixes issue: fixes https://github.com/Pirate-Weather/pirate-weather-code/issues/85
> Update VEnv docs

- API/ECMWF_Local_Ingest.py
- API/GEFS_Local_Ingest.py
- API/GFS_Local_Ingest.py
- API/HRRR_6H_Local_Ingest.py
- API/HRRR_Local_Ingest.py
- API/NBM_Fire_Local_Ingest.py
- API/NBM_Local_Ingest.py
- API/SubH_Local_Ingest.py
> 48h ingest fix V2

- API/timemachine.py
As mentioned in #197 I started updating the TimeMachine code to use the new summaries like API does. Still need to figure out the daily summary but this is a good start.
@alexander0042 You'll likely need to test as I don't have this setup to test locally.
> Start setting up translations for TimeMachine

- .github/PULL_REQUEST_TEMPLATE.md
Small change to include a step to check the version numbers to make sure the TimeMachine and API endpoints version matches.
> Add version numbers to checklist

- .gemini/config.yaml
- .gemini/styleguide.md
> Add gemini config

- API/PirateTextHelper.py
Adds a check for MISSING_DATA on visibility as it was missing in the last PR.
> Add missing visibility check

- API/PirateDailyText.py
- API/responseLocal.py
- API/timemachine.py
Only calculate the maximum smoke during low visibility hours and fix the issue where smoke was appearing outside of version 2 requests. Same fix applies for the Time Machine fields.
> Miscellaneous smoke fixes

- .gitignore
- API/ECMWF_Local_Ingest.py
- API/GEFS_Local_Ingest.py
- API/GFS_Local_Ingest.py
- API/HRRR_6H_Local_Ingest.py
- API/HRRR_Local_Ingest.py
- API/NBM_Fire_Local_Ingest.py
- API/NBM_Local_Ingest.py
- API/SubH_Local_Ingest.py
- API/ingest_utils.py
- API/responseLocal.py
Fixing a number of outstanding issues, this PR adds additional logic to the import scripts to check validity in the downloaded data and exit if it's not valid. allowing the process to restart. 
> Improve import validation

- API/responseLocal.py
- API/timemachine.py
> Update version for v2.7.5 release

- API/responseLocal.py
- API/timemachine.py
Forgot to update it in the visibility PR
> Change dev version

- API/GFS_Local_Ingest.py
Emergency patch to fix GFS ingest bug re: <https://github.com/Pirate-Weather/pirateweather/issues/472>?
> Fix ignore axis name

- .github/workflows/test.yml
- API/GFS_Local_Ingest.py
- API/HRRR_6H_Local_Ingest.py
- API/HRRR_Local_Ingest.py
- API/PirateTextHelper.py
- API/SubH_Local_Ingest.py
- API/ingest_utils.py
- API/responseLocal.py
Let's try this again. I reverted the changes as something did not like what I did and caused the development site to crash. For some reason the tests are complaining about herbie not being a module so maybe that's why it crashed? I didn't change anything with requirements so no idea why that's an issue now.
> Change minutely `precipIntensity` to use reflectivity 

- API/PirateMinutelyText.py
Small change to fix an issue where the minutely icon could be null.
> Fix minutely null icon

- API/responseLocal.py
Change snow coefficients to 200 and 2 since the old ones were incorrect.
> Modify snow coefficient in responseLocal.py

- API/GFS_Local_Ingest.py
- API/responseLocal.py
> style fixes by ruff

- API/constants/api_const.py
- API/responseLocal.py
Add the pressure unit conversion factor 
> Fix the units in the new station pressure variable
